### PR TITLE
Python3 compatibility, fulltext tag search and document update

### PR DESCRIPTION
**Pull request by dany-nonstop**
Changes made

- added compatibility with python3, change all use of django.utils.six (deprecated) to six
- added tag option ```autocomplete_fulltext``` to make full text search on autocompletion, default is off
- updated document on default setting, especially when jQuery is loaded in the other part of the project
- updated document on ```autocomplete_fulltext```
- fix "division by 0" when calling weight() on a list of new tags imported without any count (everything is 0)

they may break tagulous on python2, never tested.

### CODE REVIEW

**Comment by dany-nonstop** [comment]
@radiac I like the concise tag tree implementation in tagulous and have used it in my  python3 + django3 project. While working on my project I have added these changes to make it work. Thanks for making it available to the community.

**Comment by dany-nonstop** [comment]
@radiac whenever you're available, could you please check the code and merge them to your current branch? thanks.

**Comment by dany-nonstop** [comment]
Hi, @radiac how can I contribute my code to your project? Thanks!

**Comment by BoPeng** [comment]
I was looking for a similar features but I simply used a customized autocomplete_view function. Perhaps this is why @radiac did not want to add this as one of the core features?

**Comment by dany-nonstop** [comment]
Hi, @BoPeng your comment is highly appreciated, thanks, I would say it's a possible solution. But I don't know why @radiac didn't even care to comment before closing this PR.

**Comment by BoPeng** [comment]
I have a PR pending for more flexible view function. It is much simpler than your solution but might still not be merged. I am using a fork for my project anyway.

**Comment by radiac** [comment]
Thanks for the PR, finally had a chance to pick out the compatible changes and add some tests. Closing, merged via #128.

**Pull request closed without merging**
