### PR TITLE
Added NULLIF and quotes to SQL template

### LINKED ISSUE #59: Fatal division by zero (ORM) error when no tagged items exist
Hi,

I noticed I kept getting a division by zero error from the Django ORM when trying to fetch the tags with weights if no tagged items exist.  The error comes from the SQL query and is reproducible on the database level.  

```python
tags = SomeModel.tags.tag_model.objects.weight()
```
throws: `django.db.utils.DataError: division by zero`
try - catch doesn't seem to help either

```sql
SELECT (FLOOR((count*5)/(SELECT MAX(count)
```

Simply adding one tagged item solves this issue.
Rewriting the query as follows solves this issue as well (as dividing by NULL yields NULL), returning weight: NULL if no tagged items exist

```sql
SELECT (FLOOR((count*5)/(SELECT NULLIF(MAX(count), 0)
```

I'm just a Django / Python beginner so I don't really know how to address this issue properly.  As far as I can tell, NULLIF seems standard SQL syntax and does work on my local PGSQL server.

Kind regards,

Erik

### PR DESCRIPTION
**Pull request by 4levels**
Fixes #59 and #60

### CODE REVIEW

**Comment by 4levels** [comment]
Hmm, somehow the mysql driver doesn't like the double quoted table names..  I'll try to see if I can work around this..

**Comment by 4levels** [comment]
Allright, seems like the latest check for mysql and it's non standard use of backticks makes the build succeed for all targeted platforms in Travis..

**Comment by 4levels** [comment]
Hi @radiac,

any idea when this can be merged?  Are there any issues with my proposed changes?
It would be nice if I no longer need to resort to my own custom branch..

Thanks again!

**Comment by radiac** [comment]
Merged - finally! Thanks again!

**Pull request merged**
